"""empty message

Revision ID: 094b3006369b
Revises: 0e06f728b3c4
Create Date: 2017-08-27 10:33:30.230220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094b3006369b'
down_revision = '0e06f728b3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('closedtime', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'closedtime')
    # ### end Alembic commands ###
