"""empty message

Revision ID: 0e06f728b3c4
Revises: 7bb1331d2b41
Create Date: 2017-08-25 22:29:20.158510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e06f728b3c4'
down_revision = '7bb1331d2b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('used_mem', sa.Integer(), nullable=True))
    op.drop_column('cluster', 'uesd_mem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('uesd_mem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cluster', 'used_mem')
    # ### end Alembic commands ###
