"""empty message

Revision ID: 2cabeb98b81c
Revises: 79fe6fcadd0f
Create Date: 2017-08-25 11:23:16.271367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cabeb98b81c'
down_revision = '79fe6fcadd0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_host_ip'), 'host', ['ip'], unique=True)
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_host_ip'), table_name='host')
    # ### end Alembic commands ###
