"""empty message

Revision ID: 79fe6fcadd0f
Revises: 1789b1fe69f2
Create Date: 2017-08-25 09:57:58.435312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79fe6fcadd0f'
down_revision = '1789b1fe69f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delhost')
    op.add_column('host', sa.Column('closed', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_host_ip'), 'host', ['ip'], unique=True)
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_host_ip'), table_name='host')
    op.drop_column('host', 'closed')
    op.create_table('delhost',
    sa.Column('nu', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('htype', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('mroom', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('hostname', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('app', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('managerip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('os', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('active', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('produce', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('warranty', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('serial', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cpu', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ram', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('disk', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('storage', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('nu'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
