"""empty message

Revision ID: 7bb1331d2b41
Revises: 29c0afbb84da
Create Date: 2017-08-25 13:56:29.886289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb1331d2b41'
down_revision = '29c0afbb84da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('uesd_mem', sa.Integer(), nullable=True))
    op.add_column('cluster', sa.Column('used_cpus', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'used_cpus')
    op.drop_column('cluster', 'uesd_mem')
    # ### end Alembic commands ###
