"""empty message

Revision ID: 8a19ea8e681b
Revises: 
Create Date: 2017-08-24 09:14:35.399840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a19ea8e681b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delhost',
    sa.Column('nu', sa.Integer(), nullable=False),
    sa.Column('htype', sa.String(length=10), nullable=True),
    sa.Column('mroom', sa.String(length=6), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('hostname', sa.String(length=80), nullable=True),
    sa.Column('app', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('managerip', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('active', sa.String(length=4), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('produce', sa.String(length=20), nullable=True),
    sa.Column('warranty', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('cpu', sa.String(length=20), nullable=True),
    sa.Column('ram', sa.String(length=20), nullable=True),
    sa.Column('disk', sa.String(length=20), nullable=True),
    sa.Column('storage', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('nu')
    )
    op.create_index(op.f('ix_delhost_ip'), 'delhost', ['ip'], unique=True)
    op.add_column(u'host', sa.Column('cluster', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_host_ip'), 'host', ['ip'], unique=True)
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_host_ip'), table_name='host')
    op.drop_column(u'host', 'cluster')
    op.drop_index(op.f('ix_delhost_ip'), table_name='delhost')
    op.drop_table('delhost')
    # ### end Alembic commands ###
